### ISSUE TITLE
WARN - Azure Devops reports NODE must be upgraded  because v6 is deprecated

### ISSUE THREAD

**Issue by tlogik** [henryd24/azdevops-sonarcloud-create-project#5]
Azure Devops reports that the extension currently require Node 6.
This is EOL and developers must upgrade. Preferred latest maintained version which is 20.*
https://nodejs.org/en/download/package-manager

Error/Warning from Azure devops

##[warning]Task 'SonarCloud create project' version 1 (sonarcloud-create-project@1) is dependent on a Node version (6) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

**Comment by henryd24** [comment]
In the latest release (`v1.0.5`), the task runner was updated to the newest Node version available within the agent environment (`Node20_1`). You can review the specific changes in PR #6
